use std::time::Duration;

pub(crate) const FANQIE_VIDEO_LIST_URL: &str =
    "https://pugc.yueduwuxian.com/fqvideo/home/video-list";
pub(crate) const FANQIE_REVIEW_SCROLL_ATTEMPTS: usize = 6;
pub(crate) const FANQIE_REVIEW_SCROLL_INTERVAL: Duration = Duration::from_millis(250);
/// This script is deliberately a one-way classifier. It receives a bounded
/// title query but returns only one fixed status token, never card/page text,
/// URLs, identifiers, or selectors.
pub(crate) const FANQIE_REVIEW_STATUS_SCRIPT: &str = r#"const n=v=>String(v||'').replace(/\s+/g,'').trim();const q=n(arguments[0]);for(const card of document.querySelectorAll('.video-card')){const t=n(card.querySelector('.video-card-title')?.textContent);if(!t||!t.includes(q))continue;const s=n(card.querySelector('.video-status')?.textContent);if(/审核未通过|未通过|驳回|违规|失败/.test(s))return'rejected';if(/审核中|待审核/.test(s))return'under_review';if(/已发布|发布成功|已上线|公开|正常/.test(s))return'published';return'under_review';}window.scrollBy(0,Math.max(window.innerHeight,800));return null;"#;
/// Fanqie uses a separate publish surface from the generic video profiles.
/// Its state probes return only finite control tokens and never page content.
pub(crate) const FANQIE_PUBLISH_POLL_ATTEMPTS: usize = 30;
pub(crate) const FANQIE_PUBLISH_POLL_INTERVAL: Duration = Duration::from_millis(200);
pub(crate) const FANQIE_UPLOAD_READY_SCRIPT: &str = r#"const v=e=>{const s=getComputedStyle(e),r=e.getBoundingClientRect();return s.display!=='none'&&s.visibility!=='hidden'&&Number(s.opacity)!==0&&r.width>0&&r.height>0;};const root=document.querySelector('[data-rbd-droppable-id="album-upload-list-a"]')||document.querySelector('[class*="upload-list"]');const states=Array.from(root?.querySelectorAll('.upload-status')||[]).filter(v).map(e=>String(e.textContent||'').replace(/\s+/g,''));return states.length>0&&states.every(s=>s.includes('上传完成')||s.includes('100%'));"#;
pub(crate) const FANQIE_CHANNEL_PANEL_OPEN_SCRIPT: &str = r#"const v=e=>{const s=getComputedStyle(e),r=e.getBoundingClientRect();return s.display!=='none'&&s.visibility!=='hidden'&&Number(s.opacity)!==0&&r.width>0&&r.height>0;};const items=Array.from(document.querySelectorAll('.platform-panel-item')).filter(v);if(items.length)return'open';const candidates=Array.from(new Set(Array.from(document.querySelectorAll('.platform-panel-trigger,.publish-video-footer-left .platform-panel-trigger-text')).filter(e=>v(e)&&(e.classList.contains('platform-panel-trigger')||String(e.textContent||'').replace(/\s+/g,'').includes('发布至App'))).map(e=>e.closest('.platform-panel-trigger')||e)));if(candidates.length===0)return'missing';if(candidates.length!==1)return'ambiguous';candidates[0].click();return'opened';"#;
pub(crate) const FANQIE_CHANNEL_PANEL_VISIBLE_SCRIPT: &str = r#"const v=e=>{const s=getComputedStyle(e),r=e.getBoundingClientRect();return s.display!=='none'&&s.visibility!=='hidden'&&Number(s.opacity)!==0&&r.width>0&&r.height>0;};const items=Array.from(document.querySelectorAll('.platform-panel-item')).filter(v);if(!items.length)return false;const panels=new Set(items.map(item=>item.closest('.platform-panel')||item.parentElement));return panels.size===1;"#;
pub(crate) const FANQIE_CHANNELS_ENABLE_SCRIPT: &str = r#"const v=e=>{const s=getComputedStyle(e),r=e.getBoundingClientRect();return s.display!=='none'&&s.visibility!=='hidden'&&Number(s.opacity)!==0&&r.width>0&&r.height>0;};const items=Array.from(document.querySelectorAll('.platform-panel-item')).filter(v);const panels=new Set(items.map(item=>item.closest('.platform-panel')||item.parentElement));if(!items.length)return'missing';if(panels.size!==1)return'ambiguous';const switches=items.map(item=>item.querySelector('button[role="switch"]'));if(switches.some(sw=>!sw))return'missing';if(switches.some(sw=>sw.disabled||sw.getAttribute('aria-disabled')==='true'))return'disabled';let clicked=false;for(const sw of switches){const on=sw.getAttribute('aria-checked')==='true'||sw.classList.contains('arco-switch-checked');if(!on){sw.click();clicked=true;}}return clicked?'clicked':'selected';"#;
pub(crate) const FANQIE_CHANNELS_SELECTED_SCRIPT: &str = r#"const v=e=>{const s=getComputedStyle(e),r=e.getBoundingClientRect();return s.display!=='none'&&s.visibility!=='hidden'&&Number(s.opacity)!==0&&r.width>0&&r.height>0;};const items=Array.from(document.querySelectorAll('.platform-panel-item')).filter(v);const panels=new Set(items.map(item=>item.closest('.platform-panel')||item.parentElement));if(!items.length||panels.size!==1)return false;const switches=items.map(item=>item.querySelector('button[role="switch"]'));return switches.length===items.length&&switches.every(sw=>sw&&(sw.getAttribute('aria-checked')==='true'||sw.classList.contains('arco-switch-checked')));"#;
pub(crate) const FANQIE_ONE_CLICK_PUBLISH_READY_SCRIPT: &str = r#"const text=b=>String(b.textContent||'').replace(/\s+/g,''),v=e=>{const s=getComputedStyle(e),r=e.getBoundingClientRect();return s.display!=='none'&&s.visibility!=='hidden'&&Number(s.opacity)!==0&&r.width>0&&r.height>0;};const all=Array.from(document.querySelectorAll('button')).filter(b=>text(b).includes('一键发布'));if(!all.length)return'missing';const buttons=all.filter(v);if(!buttons.length)return'pending';if(buttons.length!==1)return'ambiguous';const button=buttons[0];return button.disabled||button.getAttribute('aria-disabled')==='true'?'disabled':'ready';"#;
pub(crate) const FANQIE_ONE_CLICK_PUBLISH_SCRIPT: &str = r#"const text=b=>String(b.textContent||'').replace(/\s+/g,''),v=e=>{const s=getComputedStyle(e),r=e.getBoundingClientRect();return s.display!=='none'&&s.visibility!=='hidden'&&Number(s.opacity)!==0&&r.width>0&&r.height>0;};const buttons=Array.from(document.querySelectorAll('button')).filter(b=>v(b)&&text(b).includes('一键发布'));if(buttons.length===0)return'missing';if(buttons.length!==1)return'ambiguous';const button=buttons[0];if(button.disabled||button.getAttribute('aria-disabled')==='true')return'disabled';button.click();return'clicked';"#;
pub(crate) const FANQIE_PUBLISH_RESULT_SCRIPT: &str = r#"const v=e=>{const s=getComputedStyle(e),r=e.getBoundingClientRect();return s.display!=='none'&&s.visibility!=='hidden'&&Number(s.opacity)!==0&&r.width>0&&r.height>0;};const notices=Array.from(document.querySelectorAll('.arco-message,.arco-notification,[class*="message"],[class*="toast"],[class*="Toast"]')).filter(v).map(e=>String(e.textContent||'').replace(/\s+/g,' '));if(notices.some(t=>/失败|错误|异常|请重试|未通过|不能为空/.test(t)))return'failure';if(notices.some(t=>/发布成功|提交成功|操作成功/.test(t)))return'success';return'pending';"#;
